#' @title lds_description_render
#' @description Render the input file to html suitable to be used in the description field of a dataset on the London DataStore.
#' @param input The input file to be rendered. This can be an R script (.R), an R Markdown document (.Rmd), or a plain markdown document.
#' @param include_title Include the YAML title in the output, Default: TRUE
#' @param ... Other parameters passed to rmarkdown::render
#' @return By default will return the rendered html string.
#' @details A markdown version of the input file is also rendered and saved.
#' @seealso \code{\link[rmarkdown]{render}}
#' @examples
#' \dontrun{
#' lds_description_render(input = "my_description.Rmd")
#' }
#' @rdname lds_description_render
#' @export
#' @importFrom checkmate assert_file_exists assert_logical
#' @importFrom rmarkdown render
lds_description_render <- function(
  input,
  include_title = FALSE,
  ...
) {
  checkmate::assert_file_exists(input, extension = c("R ", "Rmd", "md"))

  dir <- tempdir()

  rmarkdown::render(
    input = input,
    output_format = rmarkdown::html_document(),
    quiet = TRUE,
    output_dir = dir,
    ...
  )

  html_file <- list.files(tempdir(), pattern = "*.html")
  html_path <- file.path(dir, html_file)
  html <- paste(readLines(html_path), collapse = "\n")

  # Datastore description title incompatible with raw html file generated by `rmarkdown`
  if (include_title) {
    output <- fix_html_title(input_html = html, operation = "add")
  } else {
    output <- fix_html_title(input_html = html, operation = "remove")
  }

  return(output)
}

#' @title fix_html_title
#' @description Ensures that title is compatible with datastore html.
#' @param input_html A character vector.
#' @param operation A character vector - "remove" or "add"
#' @return A html string.
#' @importFrom checkmate assert_choice
#' @noRd
fix_html_title <- function(input_html, operation) {
  checkmate::assert_choice(operation, c("remove", "add"))

  html <- gsub("<title>(.*?)</title>", "", input_html)

  if (operation == "remove") {
    html <- gsub("<h2(.*?)</h2>", "", html)
    html <- gsub("<h1(.*?)</h1>", "", html)
  }

  return(html)
}
