#' @title lds_description_render
#' @description Render the input file to html suitable to be used in the description field of a dataset on the London DataStore.
#' @param input The input file to be rendered. This can be an R script (.R), an R Markdown document (.Rmd), or a plain markdown document.
#' @param output_file The name of the output file. If using NULL then the output filename will be based on filename for the input file. If a filename is provided, a path to the output file can also be provided. Note that the output_dir option allows for specifying the output file path as well, however, if also specifying the path, the directory must exist. If output_file is specified but does not have a file extension, an extension will be automatically added according to the output format. To avoid the automatic file extension, put the output_file value in I(), e.g., I('my-output'). Default: NULL
#' @param output_dir The output directory for the rendered output_file. This allows for a choice of an alternate directory to which the output file should be written (the default output directory of that of the input file). If a path is provided with a filename in output_file the directory specified here will take precedence. Please note that any directory path provided will create any necessary directories if they do not exist. Default: NULL
#' @param include_title Include the YAML title in the output, Default: TRUE
#' @param save_html Save a copy of the rendered html. The HTML will be the fragment only (no header, body, CSS etc). Default: TRUE
#' @param return_html Return a copy of the rendered html. Default: TRUE
#' @param ... Other parameters passed to rmarkdown::render
#' @return By default will return the rendered html string.
#' @details A markdown version of the input file is also rendered and saved.
#' @seealso \code{\link[rmarkdown]{render}}
#' @examples
#' \dontrun{
#' lds_description_render(input = "my_description.Rmd")
#' }
#' @rdname lds_description_render
#' @export
#' @importFrom checkmate assert_file_exists assert_logical
#' @importFrom rmarkdown render
lds_description_render <- function(
  input,
  include_title = FALSE,
  ...
) {
  checkmate::assert_file_exists(input, extension = c("R ", "Rmd", "md"))

  dir <- tempdir()

  rmarkdown::render(
    input = input,
    output_format = rmarkdown::html_document(),
    quiet = TRUE,
    output_dir = dir
  )

  html_file <- list.files(tempdir(), pattern = "*.html")
  html_path <- file.path(dir, html_file)
  html <- paste(readLines(html_path), collapse = "\n")

  # Datastore description title incompatible with raw html file generated by `rmarkdown`
  if (include_title) {
    output <- fix_html_title(input_html = html, operation = "add")
  } else {
    output <- fix_html_title(input_html = html, operation = "remove")
  }

  return(output)
}

#' @title fix_html_title
#' @description Ensures that title is compatible with datastore html.
#' @param html A character vector.
#' @param operation A character vector - "remove" or "add"
#' @return A html string.
#' @importFrom checkmate assert_choice
fix_html_title <- function(input_html, operation) {
  checkmate::assert_choice(c("remove", "add"))

  html <- gsub("<title>(.*?)</title>", "", input_html)

  if (operation == "remove") {
    html <- gsub("<h2(.*?)</h2>", "", html)
    html <- gsub("<h1(.*?)</h1>", "", html)
  }

  return(html)
}
